task_tracker/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('users.urls')),
    path('', include('tasks.urls'))
]

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)
    urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)

tasks/urls.py
from django.urls import path
from .views import LandingView, HomeView

app_name='tasks'
urlpatterns = [
    path('', LandingView.as_view(), name="landing"),
    path('home/', HomeView.as_view(), name="home"),
]

users/urls.py
from django.urls import path
from .views import UserCreation, CustomLoginView, CustomLogoutView

app_name='users'
urlpatterns = [
    path('register/', UserCreation.as_view(), name='register'),
    path('login/', CustomLoginView.as_view(), name='login'),
    path('logout/', CustomLogoutView.as_view(), name='logout'),
]

tasks/models.py
from django.db import models 
from django.contrib.auth.models import User
from django.utils import timezone
from .constants import task_status_choices, task_priority_choices

class Task(models.Model):
    '''
    Creating a model for Tasks which contains:
        - user (Foreign key relationship)
        - name
        - description
        - status
        - created_on
        - deadline
        - completed_on
    '''
    user = models.ForeignKey(User, on_delete=models.CASCADE)
    name = models.CharField('Task Name', max_length=200)
    description = models.CharField('Description', max_length=1024)
    status = models.CharField('Status', choices=task_status_choices, max_length=40)
    priority = models.CharField('Priority', choices=task_priority_choices, max_length=20)
    github_link = models.CharField('GitHub Link', max_length=200, blank=True, null=True)
    created_on = models.DateTimeField('Created On', default=timezone.now)
    deadline = models.DateTimeField('Deadline', blank=True, null=True)
    completed_on = models.DateTimeField('Completed On', blank=True, null=True)

    class Meta:
        ordering = ['deadline']

    def __str__(self):
        return f'{self.name}'

users/models.py
from django.db import models
from django.contrib.auth.models import User

class UserProfile(models.Model):
    '''
    Creating UserProfile model which links to the default auth.models for User from django.contrib
    Link - https://docs.djangoproject.com/en/3.1/topics/auth/customizing/
        - user (1 to 1 relation with the built in User)
        - user_image
        - description
    '''
    user = models.OneToOneField(User, on_delete=models.CASCADE)
    user_image = models.ImageField('User Image',upload_to='profile_pictures/', default='default_profile.jpg')
    description = models.CharField('Description', max_length=1024)
    updated_on = models.DateTimeField('Updated On', auto_now=True)

    def __str__(self):
        if self.user.first_name and self.user.last_name:
            return f"{self.user.first_name +' '+ self.user.last_name}'s Profile"
        return f"{self.user.username}'s Profile"

users/forms.py
from django import forms
from django.contrib.auth.models import User
from django.contrib.auth.forms import UserCreationForm

class RegisterUser(UserCreationForm):
    email = forms.EmailField(max_length=254, help_text="Enter a valid email address")
    
    class Meta:
        model = User
        fields = ['username', 'email', 'password1', 'password2']

tasks/views.py
from django.shortcuts import render
from django.views.generic import TemplateView, ListView
from django.contrib.auth.mixins import LoginRequiredMixin

from .models import Task

# Create your views here.
class LandingView(TemplateView):
    template_name = "tasks/index.html"

class HomeView(LoginRequiredMixin, ListView):
    login_url = '/login'
    model = Task
    context_object_name = 'tasks'
    template_name = "tasks/home.html"

users/views.py
from django.shortcuts import render

# Create your views here.
from django.urls import reverse_lazy
from django.views.generic.edit import CreateView
from .models import UserProfile
from .forms import RegisterUser
from django.contrib.auth.models import User
from django.contrib.auth.views import LoginView, LogoutView

class UserCreation(CreateView):
    '''
    Registration View
    TODO: Understand builtin methods for this class and utilize it to login the user automatically.
    TODO: Eventually add email verification for newly registered users.
    '''
    model = User
    form_class = RegisterUser
    template_name = 'users/register.html'
    success_url = reverse_lazy('tasks:home')


class CustomLoginView(LoginView):
    '''
    Login View
    TODO: TODO
    '''
    template_name = 'users/login.html'

class CustomLogoutView(LogoutView):
    next_page = reverse_lazy('users:login')

tasks/templates/dashboard.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Task Tracker</title>
</head>
<body>
    <p>{{user}}</p>
    <form action="{% url 'users:logout' %}">{% csrf_token %}<button type="submit">Logout</button></form>
    {% block body %}
    {% endblock %}
</body>
</html>

tasks/templates/tasks/home.html
{% extends 'dashboard.html' %}

<div>
{% block body %}
{% for task in tasks %}
<p>{{task.name}}</p>
{% endfor %}
{% endblock %}
</div>

tasks/templates/tasks/index.html
{% load static %}
<link href="{% static 'css/bootstrap.css' %}" rel="stylesheet" />
<link href="{% static 'css/landing_page.css' %}" rel="stylesheet" />

<!--     Fonts     -->
<link
  href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/4.1.0/css/font-awesome.css"
  rel="stylesheet"
/>
<link
  href="http://fonts.googleapis.com/css?family=Grand+Hotel"
  rel="stylesheet"
  type="text/css"
/>
<div class="main">

  <div class="cover black" data-color="blue"></div>

  <div class="container">
    <h1 class="logo">
      Task Tracker
    </h1>

    <div class="content">
      <h4 class="motto">A custom task tracker, just for you!</h4>
      <div class="subscribe">
        <h5 class="info-text">
          Join us now to try it out!
        </h5>
        <div class="row">
          <a
          href="{% url 'users:register' %}"
            class="btn btn-danger btn-fill col-xs-12 col-md-2 col-md-offset-3"
          >
            Register
        </a>
          <div class="col-xs-12 col-md-2">&nbsp;</div>
          <a
          href="{% url 'users:login' %}"
            class="btn btn-info btn-fill col-xs-12 col-md-2"
          >
            Login
        </a>
        </div>
      </div>
    </div>
  </div>
  <div class="footer">
    <div class="container">
      Made with <i class="fa fa-heart heart"></i> by
      <a href="http://github.com/ParadoxInfinite">ParadoxInfinite</a>
    </div>
  </div>
</div>
<script src="{% static 'js/jquery-1.10.2.js' %}" type="text/javascript"></script>
<script src="{% static 'js/bootstrap.min.js' %}" type="text/javascript"></script>

users/templates/users/login.html
<!-- Big up to knyttneve for this HTML + CSS Login page at https://codepen.io/knyttneve/full/JQppEw -->

{% load static %}
<link rel="stylesheet" href="{% static 'css/login_page.css' %}">
<div class="container">
  <div class="left">
    <div class="header">
      <h2 class="animation a1">Welcome Back</h2>
      <h4 class="animation a2">Log in to your account using email and password</h4>
    </div>
    <form method="POST" action="">
      <div class="form">{% if form.errors %}
        {% for field in form %}
            {% for error in field.errors %}
                <div class="alert alert-danger">
                    <strong>{{ error|escape }}</strong>
                </div>
            {% endfor %}
        {% endfor %}
        {% for error in form.non_field_errors %}
            <div class="alert alert-danger">
                <strong>{{ error|escape }}</strong>
            </div>
        {% endfor %}
    {% endif %}
        {% csrf_token %}
        <input type="text" name="{{form.username.name}}" class="form-field animation a3" placeholder="{{form.username.label}}">
        <input type="password" name="{{form.password.name}}" class="form-field animation a4" placeholder="{{form.password.label}}">
        <br>&nbsp;
        <p class="animation a5"><a href="#">Forgot Password?</a></p>
        <button class="animation a6" type="submit">LOGIN</button>
        <br>&nbsp;
        <p class="animation a7">New to <em>Task Tracker</em>? <a href="{% url 'users:register' %}">Sign Up!</a></p>
      </div>
    </form>
  </div>
  <div class="right"></div>
</div>

users/templates/users/register.html
<!-- Big up to knyttneve for this HTML + CSS Login page at https://codepen.io/knyttneve/full/JQppEw -->

{% load static %}
<link rel="stylesheet" href="{% static 'css/login_page.css' %}">
<div class="container">
  <div class="right"></div>
  <div class="left">
    <div class="header">
      <h2 class="animation a1">Welcome!</h2>
      <h4 class="animation a2">Create an account</h4>
    </div>
    <form method="POST" action="{% url 'users:register' %}">
      <div class="form">
        {% csrf_token %}
        <input type="text" name="{{form.username.name}}" class="form-field animation a3" placeholder="{{form.username.label}} {% if form.username.field.required %}*{% endif %}">
        <p class="alert animation a3">{{ form.errors.username|striptags }}</p>
        <input type="email" name="{{form.email.name}}" class="form-field animation a3" placeholder="{{form.email.label}} {% if form.email.field.required %}*{% endif %}">
        <p class="alert animation a3">{{ form.errors.email|striptags }}</p>
        <input type="password" name="{{form.password1.name}}" class="form-field animation a4" placeholder="{{form.password1.label}} {% if form.password1.field.required %}*{% endif %}">
        <p class="alert animation a4">{{ form.errors.password1|striptags }}</p>
        <input type="password" name="{{form.password2.name}}" class="form-field animation a4" placeholder="{{form.password2.label}}  {% if form.password2.field.required %}*{% endif %}">
        <p class="alert animation a4">{{ form.errors.password2|striptags }}</p>
        <br>&nbsp;
        {% if form.errors %}
        <br>&nbsp;
        {% for error in form.non_field_errors %}
            <div class="alert">
                <strong>{{ error|escape }}</strong>
            </div>
        {% endfor %}
        <br>&nbsp;
        {% endif %}
        <button class="animation a6" type="submit">Register</button>
        <br>&nbsp;
        <p class="animation a7">Already have an account? <a href="{% url 'users:login' %}">Sign In!</a></p>
      </div>
    </form>
  </div>
</div>